Matrix Operations

In [2]:
import numpy as np

2D MATRIX

In [3]:
matrix_1=np.array([[1,2],[3,4]])
print(matrix_1)

[[1 2]
 [3 4]]


3D MATRIX

In [4]:
matrix_2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


MATRIX WITH RANDOM VALUES

In [5]:
matrix_random=np.random.rand(3,3)
print(matrix_random)

[[0.82390323 0.30471534 0.40816973]
 [0.6203481  0.15363198 0.58844126]
 [0.44784281 0.65364125 0.44591485]]


MATRIX WITH RANDOM INTEGERS

In [6]:
matrix_random_integers=np.random.randint(100,size=(4,4))
print(matrix_random_integers)

[[76 14 24 58]
 [65 16 76 38]
 [10 46 44 13]
 [58 66 87 18]]


MATRIX WITH ALL ONES

In [7]:
matrix_ones=np.ones((2,2))
print(matrix_ones)

[[1. 1.]
 [1. 1.]]


matrix with all ones and dtype=int

In [8]:
matrix_intones=np.ones((2,2),dtype=int)
print(matrix_intones)

[[1 1]
 [1 1]]


In [9]:
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


transpose of a matrix

In [10]:
matrix_random=np.random.randint(100,size=(4,4))
print(matrix_random)

[[43 80 51  4]
 [44 92  7 88]
 [31 78 66  4]
 [86 80 74 70]]


In [11]:
transpose_matrix=np.transpose(matrix_random)
print(transpose_matrix)

[[43 44 31 86]
 [80 92 78 80]
 [51  7 66 74]
 [ 4 88  4 70]]


Matrix Additition

In [12]:
matrix_1=np.array([[2,3],[3,4]])
matrix_2=np.array([[4,5],[8,9]])

In [13]:
addition=matrix_1+matrix_2
print(addition)

[[ 6  8]
 [11 13]]


Matrix Subtraction

In [14]:
matrix_1=np.array([[2,3],[3,4]])
matrix_2=np.array([[4,5],[8,9]])

In [15]:
subtraction=matrix_1-matrix_2
print(subtraction)

[[-2 -2]
 [-5 -5]]
